classDiagram
  VirtualEntity <|-- AbstractCostRecord
  PerformanceProperty <|-- AcousticProperty
  Entity <|-- Agent
  PhysicalElement <|-- Boundary
  Agent <|-- Company
  PhysicalElement <|-- ConnectionPhysical
  VirtualEntity <|-- ConnectionVirtual
  PhysicalElement <|-- Equipment
  PerformanceProperty <|-- FireProperty
  VirtualEntity <|-- Material
  PerformanceProperty <|-- MaterialProperty
  Entity <|-- Message
  ScheduleItem <|-- Milestone
  Agent <|-- Person
  Entity <|-- PhysicalElement
  Entity <|-- ScheduleDependency
  Entity <|-- ScheduleItem
  Entity <|-- ScheduleTemplate
  PerformanceProperty <|-- SecurityProperty
  PhysicalElement <|-- Separator
  VirtualEntity <|-- Space
  VirtualEntity <|-- SpatialContext
  PerformanceProperty <|-- StructuralProperty
  VirtualEntity <|-- System
  PerformanceProperty <|-- ThermalProperty
  Entity <|-- VirtualEntity
