classDiagram
  VirtualEntity <|-- AbstractCostRecord
  PerformanceProperty <|-- AcousticProperty
  Entity <|-- Agent
  PhysicalElement <|-- Boundary
  BuiltAssetContext <|-- BuildingContext
  SpatialContext <|-- BuiltAssetContext
  BuiltAssetContext <|-- CivilStructureContext
  Agent <|-- Company
  PhysicalElement <|-- ConnectionPhysical
  VirtualEntity <|-- ConnectionVirtual
  AbstractCostRecord <|-- CostAssembly
  AbstractCostRecord <|-- CostItem
  PhysicalElement <|-- Equipment
  PerformanceProperty <|-- FireProperty
  SpatialContext <|-- LegalSiteContext
  SpatialContext <|-- LevelContext
  VirtualEntity <|-- Material
  PerformanceProperty <|-- MaterialProperty
  Entity <|-- Message
  ScheduleItem <|-- Milestone
  SpatialContext <|-- PerimeterContext
  Agent <|-- Person
  Entity <|-- PhysicalElement
  SpatialContext <|-- ProjectContext
  Entity <|-- ScheduleDependency
  Entity <|-- ScheduleItem
  Entity <|-- ScheduleTemplate
  PerformanceProperty <|-- SecurityProperty
  PhysicalElement <|-- Separator
  Separator <|-- SeparatorSlab
  Separator <|-- SeparatorWall
  VirtualEntity <|-- Space
  VirtualEntity <|-- SpatialContext
  PerformanceProperty <|-- StructuralProperty
  VirtualEntity <|-- System
  PerformanceProperty <|-- ThermalProperty
  Entity <|-- VirtualEntity
  SpatialContext <|-- ZoneContext
