flowchart TB
  Root["Pragmatic BIM Data Contract"]
  Root --> shared_enums["Shared Enums"]
  click shared_enums href "./shared/enums/" _blank
  Root --> entity_core["Entity Core"]
  click entity_core href "./entity/core/" _blank
  Root --> entity_enums["Entity Enums"]
  click entity_enums href "./entity/enums/" _blank
  Root --> entity_performance_enums["Entity Performance Enums"]
  click entity_performance_enums href "./entity/performance-enums/" _blank
  Root --> entity_performance["Entity Performance"]
  click entity_performance href "./entity/performance/" _blank
  Root --> entity_physical["Entity Physical"]
  click entity_physical href "./entity/physical/" _blank
  Root --> entity_virtual["Entity Virtual"]
  click entity_virtual href "./entity/virtual/" _blank
  Root --> requirements_enums["Requirements Enums"]
  click requirements_enums href "./requirements/enums/" _blank
  Root --> requirements["Requirements"]
  click requirements href "./requirements/" _blank
  Root --> changes_enums["Changes Enums"]
  click changes_enums href "./changes/enums/" _blank
  Root --> changes["Changes"]
  click changes href "./changes/" _blank
