flowchart TB
  Root["Pragmatic BIM Data Contract"]
  Root --> core["Core"]
  click core href "./core.html" _blank
  Root --> performance_enums["Performance Enums"]
  click performance_enums href "./performance-enums.html" _blank
  Root --> requirements_enums["Requirements Enums"]
  click requirements_enums href "./requirements-enums.html" _blank
  Root --> performance["Performance"]
  click performance href "./performance.html" _blank
  Root --> requirements["Requirements"]
  click requirements href "./requirements.html" _blank
  Root --> elements_physical["Elements Physical"]
  click elements_physical href "./elements-physical.html" _blank
  Root --> elements_virtual["Elements Virtual"]
  click elements_virtual href "./elements-virtual.html" _blank
  Root --> enums["Enums"]
  click enums href "./enums.html" _blank
  Root --> changes["Changes"]
  click changes href "./changes.html" _blank
