classDiagram
  direction TB
  Change <|-- AdditionChange
  Change <|-- DeletionChange
  Change <|-- GeometryChange
  Change <|-- MatchChange
  Change <|-- PropertyChange
  Change <|-- RequirementChange
  ChangeSet *-- Change
