classDiagram
  VirtualEntity <|-- AbstractCostRecord
  BuiltAssetContext <|-- BuildingContext
  SpatialContext <|-- BuiltAssetContext
  BuiltAssetContext <|-- CivilStructureContext
  VirtualEntity <|-- ConnectionVirtual
  AbstractCostRecord <|-- CostAssembly
  AbstractCostRecord <|-- CostItem
  SpatialContext <|-- LegalSiteContext
  SpatialContext <|-- LevelContext
  VirtualEntity <|-- Material
  ScheduleItem <|-- Milestone
  SpatialContext <|-- PerimeterContext
  SpatialContext <|-- ProjectContext
  Entity <|-- ScheduleDependency
  Entity <|-- ScheduleItem
  Entity <|-- ScheduleTemplate
  VirtualEntity <|-- Space
  VirtualEntity <|-- SpatialContext
  VirtualEntity <|-- System
  Entity <|-- VirtualEntity
  SpatialContext <|-- ZoneContext
